name: Log Wallet Balance

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:      # Allow manual trigger

jobs:
  update-balance-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios fs

      - name: Run balance logger
        run: node .github/scripts/log-balance.js
        env:
          ETH_ADDRESS: 0xb96e27d05fe60a24a01a7672e7d3effc3bdb3d7e
          BTC_ADDRESS: bc1qjtgfw6dythprkvmkps7dmfm7dkkhtgy76q02ep
          ETHERSCAN_API_KEY: 7HQVBFNBCEAYW31Z1B9V7W7G56KPR2XECW

      - name: Commit and push log
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add balance-history.json
          git commit -m "Update balance log"
          git push
